# Generated by Django 4.0.1 on 2022-01-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_playerstatistics_team_league_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistics',
            name='player_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='player_statistics', to='api.players'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamsLeaguesSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.leagues')),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.seasons')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='api.teams')),
            ],
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='team_league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_statistics', to='api.teamsleaguesseasons'),
        ),
        migrations.DeleteModel(
            name='TeamsPlayersLeaguesSeasons',
        ),
    ]
