# Generated by Django 4.0.1 on 2022-01-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_leaguesseasons_remove_teamsleaguesseasons_leagues_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesseasons',
            name='leagues_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seson', to='api.leagues'),
        ),
        migrations.AlterField(
            model_name='leaguesseasons',
            name='seasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leage', to='api.seasons'),
        ),
    ]
