# Generated by Django 4.0.1 on 2022-01-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_leaguesseasons_leagues_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaguesSeasons',
        ),
    ]
