# Generated by Django 4.0.1 on 2022-01-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('nationality', models.CharField(max_length=125, null=True, unique=True)),
                ('flag', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('capacity', models.PositiveIntegerField()),
                ('country_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stadiums', to='api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('logo', models.URLField(null=True)),
                ('national', models.BooleanField()),
                ('founded', models.PositiveSmallIntegerField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.countries')),
                ('stadiums_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.stadiums')),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(null=True)),
                ('type', models.CharField(max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=1000)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leagues', to='api.countries')),
                ('seasons', models.ManyToManyField(blank=True, related_name='leagues', to='api.Seasons')),
            ],
        ),
    ]
