# Generated by Django 4.0.1 on 2022-01-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_teams_founded'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.URLField()),
                ('position', models.CharField(max_length=25)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='api.countries')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='api.teams')),
            ],
        ),
    ]
