# Generated by Django 4.0.1 on 2022-01-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='status',
        ),
        migrations.AddField(
            model_name='players',
            name='injured',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
