# Generated by Django 4.0.1 on 2022-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_players_status_players_injured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team_id',
        ),
        migrations.AddField(
            model_name='players',
            name='team_id',
            field=models.ManyToManyField(blank=True, related_name='players', to='api.Teams'),
        ),
    ]
