# Generated by Django 4.0.1 on 2022-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_players_team_id_players_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='last',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
