# Generated by Django 4.0.1 on 2022-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_players_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='leagues', to='api.Teams'),
        ),
    ]
