# Generated by Django 4.0.1 on 2022-01-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_leagues_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='api.Teams'),
        ),
    ]
