# Generated by Django 4.0.1 on 2022-01-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_leagues_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='teams',
        ),
    ]
