# Generated by Django 4.0.1 on 2022-01-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_leagues_seasons_remove_leagues_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesSeasonsTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seasons', to='api.leagues')),
                ('seasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leagues', to='api.seasons')),
                ('team_id', models.ManyToManyField(blank=True, related_name='leagues', to='api.Teams')),
            ],
        ),
    ]
