# Generated by Django 4.0.1 on 2022-01-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_leaguesseasonsteams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesseasonsteams',
            name='leagues_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='seasons', to='api.leagues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaguesseasonsteams',
            name='seasons',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='leagues', to='api.seasons'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaguesseasonsteams',
            name='team_id',
            field=models.ManyToManyField(related_name='leagues', to='api.Teams'),
        ),
    ]
