# Generated by Django 4.0.1 on 2022-01-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_leaguesseasonsteams_leagues_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='nationality',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='founded',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='stadiums_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.stadiums'),
        ),
    ]
