# Generated by Django 4.0.1 on 2022-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_countries_nationality_alter_leagues_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
