# Generated by Django 4.0.1 on 2022-01-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_players_injured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team_id',
        ),
        migrations.CreateModel(
            name='TeamsPlayersLeaguesSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.leagues')),
                ('player_id', models.ManyToManyField(blank=True, related_name='teams', to='api.Players')),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.seasons')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='api.teams')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=25)),
                ('rating', models.CharField(max_length=15)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('captain', models.BooleanField(default=False)),
                ('substitutes_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('substitutes_out', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('substitutes_bench', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_conceded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_key', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passes_accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tackles_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tackles_blocks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tackles_interceptions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duels_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duels_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dribbles_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dribbles_success', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_drawn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fouls_committed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cards_yellow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cards_yellowred', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cards_red', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_commited', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_scored', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_missed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalty_saved', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_league_season', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_statistics', to='api.leagues')),
            ],
        ),
    ]
