# Generated by Django 4.0.1 on 2022-01-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_playerstatistics_team_league_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seson', to='api.leagues')),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leage', to='api.seasons')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamsplayersleaguesseasons',
            name='leagues_id',
        ),
        migrations.RemoveField(
            model_name='teamsplayersleaguesseasons',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='teamsplayersleaguesseasons',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='teamsplayersleaguesseasons',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
        migrations.DeleteModel(
            name='TeamsPlayersLeaguesSeasons',
        ),
    ]
