# Generated by Django 4.0.1 on 2022-01-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_leaguesseasons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesSeasonsTeamss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaguesSeasons', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.leaguesseasons')),
                ('team_id', models.ManyToManyField(related_name='leaguess', to='api.Teams')),
            ],
        ),
    ]
